categories:
  - title: '⚠️ Breaking changes'
    label: 'BREAKING CHANGES'

  - title: '🚀 Features'
    labels:
      - 'Feature'
      - 'Enhancement'

  - title: '🐛 Bug Fixes'
    labels:
      - 'Fix'
      - 'Bugfix'
      - 'Bug'

  - title: '🛠 Refactor'
    label: 'Refactor'

  - title: '💅 Style'
    label: 'Style'

  - title: '🧰 Maintenance'
    labels:
      - 'Chore'
      - 'Dependencies'
      - 'CI'

  - title: '📚 Documentation'
    label: 'Documentation'

  - title: '🧪 Tests'
    label: 'Tests'

  - title: '🏎 Optimizations'
    label: 'Optimizations'

version-resolver:
  major:
    labels:
      - 'BREAKING CHANGES'
  minor:
    labels:
      - 'Feature'
      - 'Enhancement'
      - 'Dependencies'
  patch:
    labels:
      - 'Fix'
      - 'Bugfix'
      - 'Bug'
      - 'Optimizations'
      - 'Refactor'
      - 'Style'
  default: patch

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

change-template: '- $TITLE #$NUMBER (@$AUTHOR)'
template: |
  $CHANGES